apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-nginx
  template:
    metadata:
      labels:
        app: django-nginx
    spec:
      containers:
        - name: django-nginx
          image: lhi90/django-nginx:0.1
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: my-secret